### ISSUE TITLE
Problem fetching assets (isn't precompiled)

### ISSUE THREAD

**Issue by jarthod** [ndbroadbent/turbo-sprockets-rails3#6]
I tried this gem on 3 totally different rails application (**3.2.3** and **3.2.8** all with ruby **1.9.3**) and got the same issue on each:
### ActionView::Template::Error (---------- isn't precompiled)

The assets precompile fine, with the new manifest format:

``` yml

---
:source_digests:
  !binary "YmcucG5n": be970f93cd2fba93cbef8e9fa4d29b1b
  !binary "YmcyLnBuZw==": 6286f069f6ea35f1e3684e4843d83a19
  ...
:digest_files:
  !binary "YmcucG5n": bg-be970f93cd2fba93cbef8e9fa4d29b1b.png
  !binary "YmcyLnBuZw==": bg2-6286f069f6ea35f1e3684e4843d83a19.png
  ...
```

But the application does not find the assets here for example:

``` ruby
= stylesheet_link_tag "application", :media => "all"
```

The issue seems to be with all assets.
I tried running the application with your gem, but using the OLD `manifest.yml` and is seems to work.

So I guess this has to do with the way Rails find assets in this file, which is not patched for the new syntax or something like that ?

I'll try to investigate more but if you have any idea that would be cool ;D

**Comment by sbounmy** [comment]
+1 same here

**Comment by ndbroadbent** [comment]
Hi there, sorry you are experiencing this problem, and thanks for raising an issue!

The problem looks like it comes from the `!binary "YmcucG5n"` keys. Those should just be plain strings like 'application.css', etc. For the record, your `manifest.yml` should look like this:

``` yaml
:source_digests:
  application.js: 92c8fd5f66eb97b1046fefb7ab1850b7
  application.css: b0d401054b182b17d2df21d719a6d16e
  ...
:digest_files:
  application.js: application-aa9a8384a1df1d0971985ae44a86b7b0.js
  application.css: application-10cc8f9a51c7320a5fc130258e619cba.css
  ...
```

I've just tried to solve this issue by using `encode("UTF-8")` for Ruby 1.9.x. I was already doing it for the digest strings, but didn't realize that asset filenames might also be affected by string encoding issues.

Please update the gem version to ~~0.1.6~~ `0.1.7` and try again. After updating, let me know if the asset keys in your `manifest.yml` file are now regular strings, and if this solves your problem.

Cheers!
